# Generated by Django 6.0.5 on 2026-06-11 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first_name', models.CharField(max_length=30, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='sobrenome')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='fone')),
                ('lens_type', models.CharField(blank=True, choices=[('mp', 'Multifocal - Policarbonato'), ('mo', 'Multifocal - Orgânica'), ('mc', 'Multifocal - Cristal'), ('sp', 'Visão Simples - Policarbonato'), ('so', 'Visão Simples - Orgânica'), ('sc', 'Visão Simples - Cristal')], max_length=2, verbose_name='tipo de lente')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='data de entrada')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='data de entrega')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('frame_type', models.CharField(blank=True, max_length=50, verbose_name='tipo de armação')),
                ('last_purchase', models.DateField(blank=True, null=True, verbose_name='ultima compra')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='aniversario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='nome do médico')),
                ('issued_at', models.DateField(verbose_name='data da receita')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('far_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Longe - Direito')),
                ('far_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Longe - Esquerdo')),
                ('near_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perto - Direito')),
                ('near_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perto - Esquerdo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='client.client')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='EyePrescriptionMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eixo - Direito')),
                ('dnp_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distância Noso Pupilas - Direito')),
                ('height_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura - Direito')),
                ('axis_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eixo - Esquerdo')),
                ('dnp_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distância Noso Pupilas - Esquerdo')),
                ('height_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura - Esquerdo')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='client.prescription')),
            ],
            options={
                'verbose_name': 'Medida da Receita',
                'verbose_name_plural': 'Medidas das Receitas',
            },
        ),
    ]
